### ISSUE TITLE
Suite yml is updated to point to latest release versions of components

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-oss-suite-release#121]
Our suite yml is currently pointing to versions of components that are not newest (intentionally). We need to update the suite.yml to actually point to the newest ones.

AC:
- [ ] Suite.yml versions are updated to point to the latest ones

**Comment by sgnn7** [comment]
@izgeri - I'm guessing this might be on your plate maybe?

**Comment by izgeri** [comment]
I'm going to close this issue as a duplicate of #32 - feel free to create a draft suite YML bump as needed (@sgnn7 suggested the playroom)
