### ISSUE TITLE
OSS suite has a versioning explanation and policy

### ISSUE THREAD

**Issue by alexkalish** [cyberark/conjur-oss-suite-release#159]
After significant work and debate, we arrived at a versioning policy for the Conjur OSS Suite that is directly dependent upon the the Conjur version included in the release.  Essentially, it will be `x.y.z+suite.n`, where `x.y.z` is the Conjur version and `n` is an integer incremented for each suite release using the same Conjur version.  The latter component will likely not be incremented often.  This is a fairly straightforward and easy to understand scheme, but it still needs to be communicated to both user and contributors of this repo.  With that in mind, I would suggest addition of the following:

1. [x] Add a small section to the `README` explaining what our versions mean and how they relate to Conjur.  This is only intended for users.
2. [x] Add larger section to the `CONTRIBUTING` file explaining how a version number is determined, so that contributors conducting releases can decide which version to use for each release.
3. [x] File a separate issue so that the content in first todo/bullet above is also added to the docs.conjur.org site.  This will ensure that users understand our versioning, regardless of how they consume the suite.
4. [ ] (Optional) As said above, significant thought was put into this scheme.  I think there is value in publishing this in a public place.  Maybe we need a `designs` directory or it could go into the wiki.

**Comment by izgeri** [comment]
Filed cyberark/conjur-docs#890
