### ISSUE TITLE
README briefly explains purpose/value of the project

### ISSUE THREAD

**Issue by alexkalish** [cyberark/conjur-oss-suite-release#160]
At the moment, the `README` for this repo is too terse, as it's aimed primarily at contributors working to complete the first release.  It has served this process well, but as we prepare for the first release, it needs to provide a bit more context for users of the suite.  Thus, I would propose the following changes:

* [x] Add a section at the top of the doc that explains what this repo is and why someone might care about it.  Likely, this content can be largely lifted from the [design doc](https://github.com/cyberark/conjur/blob/master/design/oss_suite_release.md).
* [x] Add a section that explains to users how that might use this repo.  This might largely be a link to the "Releases" page.
* [x] Rename or reposition the current usage section that it's clear why someone would execute the changelog CLI.
* [ ] (Optional) Edit the [cyberark/conjur](https://github.com/cyberark/conjur) `README` file so that it has a link and brief description of the suite.

**Comment by izgeri** [comment]
Leaving the last optional bullet for #45
