### ISSUE TITLE
Extracts additional version info from GH release

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/conjur-oss-suite-release#22]
> the suite release CHANGELOG is auto-generated from the CHANGELOGs of individual components
it was proposed that the additional version info (notable updates, upgrade instructions, and known issues) was put in gh releases - so our suite release automation would additionally have to parse gh release descriptions to get this info

By parsing Github Releases we can gather addition information for a component release and add it to the combined changelog

**Comment by izgeri** [comment]
closing this in favor of #68, which makes it possible for components to provide the suite release with an upgrade URL that can be linked to in the release notes

future updates that make this possible may still happen, but for now this is not planned work and we are closing this issue.
