### ISSUE TITLE
Document all artifact types and locations

### ISSUE THREAD

**Issue by alexkalish** [cyberark/conjur-oss-suite-release#228]
I've asked to provide a list of all artifact types that we build and distribute.  The CyberArk org is moving towards cryptographically signing all artifacts.  To start, they need to know exactly which types we create.  However, additionally, it would just be helpful for us know this as well, for our own knowledge.

Regarding the integrations to review, I think it's safe if we just looked at all the ones in the [suite release](https://github.com/cyberark/conjur-oss-suite-release/blob/main/suite.yml).

AC
- [x] Go through each repo/entry in the suite release and document the following:
    * Type of artifact produced for release (e.g. JAR, Rubygem, etc).
    * Distribution location for the artifact (e.g. GitHub releases, rubygems.org, etc), with link.
    * Whether it's a manual or automatic process to create the artifact

For now, I think it's fine to just document this in the issue.  Not sure I have a better place for it.

**Comment by alexkalish** [comment]
FYI, @andytinkham, feel free to suggest anything else you might want to know.

@jtuttle: Let's include this in grooming next week, but I'm going to guess it's like a 1 pointer.

**Comment by jtuttle** [comment]
It would also be useful for Andy to know if it's a manual or automatic process to create each artifact.

**Comment by imheresamir** [comment]
|Category                      |Repository   |Artifact Type   |Distribution Location   |Automated Creation   |
|------------------------------|---|---|---|---|
|Conjur Server              |   |   |   |   |
|Conjur Server              |   |   |   |   |
|Conjur Server              |   |   |   |   |
|Conjur SDK                 |   |   |   |   |
|Conjur SDK                 |   |   |   |   |
|Conjur SDK                 |   |   |   |   |
|Conjur SDK                 |   |   |   |   |
|Conjur SDK                 |   |   |   |   |
|Conjur SDK                 |   |   |   |   |
|Platform Integrations   |   |   |   |   |
|Platform Integrations   |   |   |   |   |
|Platform Integrations   |   |   |   |   |
|Platform Integrations   |   |   |   |   |
|DevOps Tools             |   |   |   |   |
|DevOps Tools             |   |   |   |   |
|DevOps Tools             |   |   |   |   |
|DevOps Tools             |   |   |   |   |
|Secretless Broker       |   |   |   |   |
|Summon                     |   |   |   |   |
|Summon                     |   |   |   |   |

**Comment by doodlesbykumbi** [comment]
Nice work @imheresamir. I wonder if it might be worth it to extending the spec of suite.yml in this repo to include this information for each component, see 
https://github.com/cyberark/conjur-oss-suite-release/blob/main/suite.yml. That would give this information a fixed place to live and allow it to evolve as new components are added

**Comment by alexkalish** [comment]
Great research!  Definitely want to put this content somewhere more permanent, though I don't have a strong opinion.  Could be `suite.yml` as Kumbi said.  Or into the Wiki?  Or a `*.md` file?

**Comment by andytinkham** [comment]
Wow - this is fantastic. Thanks, @imheresamir. I'm with Alex & Kumbi - we want to preserve this, but I don't have a strong opinion as long as I know where it is. 😁

**Comment by andytinkham** [comment]
@adamouamani - you may find this useful for your work too.
