### ISSUE TITLE
There is a script to auto-generate data on unreleased features

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-oss-suite-release#3]
Given that the repo has a list of components and pinned versions
And some of the components have github tags newer than the pinned version in the suite
Then there is a script that can generate a list of the newer versions available
And the output of the script includes links to the new GitHub releases available
And (optionally) the output of the script includes the descriptions from the new GitHub releases available

**Comment by sgnn7** [comment]
@izgeri / @alexkalish: I think we need a clarification here to understand the desired output. Is "unreleased":
- Versions of a component that are released but not released as part of the suite
- Versions of a component that are unreleased in both the component and suite
- All of the above

**Comment by izgeri** [comment]
At a minimum, the output of this script should include the changelogs of all component versions that were tagged after the latest suite release version of that component

So if the latest suite release includes Ansible 1.5.1, and we've since tagged 1.5.2 and 1.6.0, the "unreleased" script would include the changelogs from 1.5.2 and 1.6.0

This helps answer the question "are there new component versions that we could include in a new suite release?"

At a minimum, we would also like to understand whether there are untagged changes in any components to help answer the question "are there outstanding changes that could/should be rolled into a tagged component version so that we can include them in the next suite release?".

The "nice to have" is a changelog with the component changes that are not yet in a tagged release, but even just flagging that "Component A has changes on master since the latest tag" is useful info.

**Comment by sgnn7** [comment]
Current direction of what I am outputting in my WIP for this: https://gist.github.com/sgnn7/864025a92f277cdf9e4635a0cc38bbee

CC: @alexkalish 

We may need to split out the `whether there are untagged changes in any components` into a different story as that may need some architectural changes.
