### ISSUE TITLE
Convert GitHub release notes into website template release notes format 

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-oss-suite-release#35]
Based on the template provided by the TWs in cyberark/conjur-docs#717, enable outputting the suite release notes in the documentation format and automatically submitting a PR to the docs repo with the new template added to the suite.

AC:
- [ ] Automation can output release notes in the documentation template format
- [ ] Automation ensures a PR is opened on the docs repo with the new suite release notes page

Note from the docs issue:
- These files can go in the `Content/ReleaseNotes` folder in cyberark/conjur-docs when they're generated
- The files should be named `ConjurSuite_v{{ suite_version }}.htm`

**Comment by izgeri** [comment]
Here is what the template should look like, broken out into sections:

## Top section
Data to replace:
- {{ suite_release_version }}
- {{ suite_components_list }} - see the section on this below
- {{ upgrade_instructions_list }} - see the section on this below
- {{ changed_components_list }} - see the section on this below
- {{ changes_by_component_list }} - see the section on this below
```html
<?xml version="1.0" encoding="utf-8"?>
<html xmlns:MadCap="http://www.madcapsoftware.com/Schemas/MadCap.xsd">
<head></head>
<body>
  <h1>Release Notes</h1>
  <p>The following features were introduced or enhanced in the Conjur OSS suite v{{ suite_release_version }} release.</p>

<h2>Components</h2>
<p>These are the components that comprise the Conjur Open Source Suite with links to their GitHub releases:</p>
<p>
  <ul>
     {{ suite_components_list }}
  </ul>
</p>

<h2>Upgrade Instructions</h2>
<p>Upgrade instructions are available for the following suite components:</p>
<p>
  <ul>
    {{ upgrade_instructions_list }}
  </ul>
</p>

<h2>What's New by Component</h2>
<p>
  <ul>
    {{ changed_components_list }}
  </ul>
</p>

{{ changes_by_component_list }}
```

## Suite components list
Each entry in this list is of the form that follows, where the following values are replaced:
- {{ repo }}
- {{ component_version }}
- {{ component_release_date }}
```html
    <li><a href="https://github.com/cyberark/{{ repo }}/releases/tag/v{{ component_version }}">cyberark/{{ repo }} v{{ component_version }}</a> ({{ component_release_date }})</li>
```

## Upgrade instructions list
Each entry in this list is of the form that follows, where the following values are replaced:
- {{ component_upgrade_url }}
- {{ repo }}
```html
    <li><a href="{{ component_upgrade_url }} ">cyberark/{{ repo }}</a></li>
```

## Changed components list
Each entry in this list is of the form that follows, where the following values are replaced:
- {{ repo }}
```html
    <li><MadCap:xref href="#cyberark-{{ repo }}">cyberark/{{ repo }}</MadCap:xref></li>
```

## Changes by component list
For each component with changes, include a section of the form below where the following values are replaced:
- {{ repo }}
- {{ component_changes_by_version_list }} - see below for definition, one entry for each version of the component that has changed since the last release. the versions should be listed in reverse chronological order, with the latest (the version pinned in the suite release) on top
```html
<h3><a name="cyberark-{{ repo }}"></a>cyberark/{{ repo }}</h3>
{{ component_changes_by_version_list }}
```

## Component changes by version list
Each entry in this list is of the form that follows, where the following values are replaced:
- {{ repo }}
- {{ component_version }}
- {{ component_release_date }}
- {{ component_version_changelog }} - this is a bulleted list with the CHANGELOG entries for the version - primary bullets are the standard Added / Changed / Fixed / etc wrapped in `<strong></strong>`, and sub-bullets are the actual changes.
```html
<h4><a href="https://github.com/cyberark/{{ repo }}/releases/tag/v{{ component_version }}">v{{ component_version }}</a> ({{ component_release_date }})</h4>
<p>
  <ul>
    {{ component_version_changelog }}
  </ul>
</p>
```

## Bottom
The bottom of the page should have the end tags for the body/html elements.
```html
  </body>
</html>
```

**Comment by izgeri** [comment]
Here is a (manually generated) example that uses this format:
- [original github release notes](https://gist.github.com/BradleyBoutcher/a7d433f20afb336f7ebf3a126bb325dd#cyberarkconjur) (from Bradley)
- [sample draft htm release notes](https://gist.github.com/izgeri/91c8084cf838edf5897f3994640c0c92)

**Comment by sgnn7** [comment]
This may take a touch longer than originally anticipated (though 3 days may be enough):
- HTML templates need a different package for serialization to do proper escaping (`html/template` instead of `text/template`)
- HTML needs more anchor logic (slashes won't work)
- HTML needs conversion of markdown links (`[name](url)`) into anchor links (`<a href="url">name</a>`)

**Comment by izgeri** [comment]
@sgnn7 if we have to manually create the docs PR for now, that's probably ok

**Comment by sgnn7** [comment]
@izgeri first bullet point is implemented and merged already. I already have a pseudo template for the html generation that I can finish up asap and the anchor stuff and links can be a manual cleanup part for now. WDYT?

**Comment by izgeri** [comment]
why don't you send me what you have once the html output is in a reasonable place (eg whatever you can "finish up asap") and we'll figure out what manual steps will be left from there to see if we want to log any follow-up work to further automate it.

**Comment by sgnn7** [comment]
👍 - will do that Monday
