### ISSUE TITLE
Suite release can be auto-generated in build pipeline

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-oss-suite-release#38]
The master branch pipeline automatically publishes releases based on new github tags.

**Comment by sgnn7** [comment]
`The GH API call for creating a release can also create the tag` won't seem to work - this is only true when using the UI (api [doesn't have that](https://developer.github.com/v3/repos/releases/#input)). 

I think doing the first flow might be the better option here and we can automate it using GH actions afaict.
