### ISSUE TITLE
Each suite component repo has a tagged release that meets suite requirements

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-oss-suite-release#43]
- [x] Review all components in the suite release to determine whether they meet the standards for gh tags / releases defined in #42, and fix them if not.
- [x] Ensure each repo has documented guidelines that match our standards in their CONTRIBUTING.md section on releasing

**Comment by izgeri** [comment]
Note from @sgnn7:
- go through each repo in suite.yml
- see if releases are current (eg there is a release associated with the latest tag)
- verify the latest tag is annotated
- verify the latest release has a copy of the changelog for that version in it
- document whatever is missing on this issue

**Comment by izgeri** [comment]
Note: this is all resolved, except for the cyberark/conjur-api-dotnet project, which has no tags. We did not include it in the first release

We still need to verify:
- Does each release look correct in the unreleased changes page?
- Does each most recent tag for each component actually correspond to an artifact with the same version?

**Comment by doodlesbykumbi** [comment]
@izgeri Could you please elaborate on what correct means here?
> Does each release look correct in the unreleased changes page?

---
Managed to get answers to the second question via some automation, see the results below.
```bash
cat << EOL | while read LINE; do;
cyberark/conjur
cyberark/conjur-oss-helm-chart
cyberark/conjur-aws
cyberark/conjur-cli
cyberark/conjur-api-dotnet
cyberark/conjur-api-go
cyberark/conjur-api-java
cyberark/conjur-api-python3
cyberark/conjur-api-ruby
cyberark/conjur-authn-k8s-client
cyberark/secrets-provider-for-k8s
cyberark/conjur-service-broker
cyberark/cloudfoundry-conjur-buildpack
cyberark/ansible-conjur-host-identity
cyberark/conjur-credentials-plugin
cyberark/conjur-puppet
cyberark/terraform-provider-conjur
cyberark/secretless-broker
cyberark/summon
cyberark/summon-aws-secrets
cyberark/summon-chefapi
cyberark/summon-conjur
cyberark/summon-keyring
cyberark/summon-s3
EOL
  echo "---"
  echo "${LINE}"
  latest_tag=$(hub api "/repos/${LINE}/tags" | jq -r 'sort_by(.name) | reverse | .[0].name')
  echo "latest tag is ${latest_tag}"
  hub api "/repos/${LINE}/releases" | jq 'map(select(.tag_name == "'${latest_tag}'")) | map("name: \(.name), tag_name: \(.tag_name)")'
done

```

Results below. Note: 
1.`latest tag is null` means there are no tags
2. `[]` after the latest tag, means there are no releases using that tag

```
---
cyberark/conjur
latest tag is v1.5.1
[
  "name: v1.5.1, tag_name: v1.5.1"
]
---
cyberark/conjur-oss-helm-chart
latest tag is v1.3.8
[
  "name: v1.3.8, tag_name: v1.3.8"
]
---
cyberark/conjur-aws
latest tag is null
[]
---
cyberark/conjur-cli
latest tag is v6.2.1
[
  "name: v6.2.1, tag_name: v6.2.1"
]
---
cyberark/conjur-api-dotnet
latest tag is v1.4.0
[
  "name: v1.4.0, tag_name: v1.4.0"
]
---
cyberark/conjur-api-go
latest tag is v0.6.0
[
  "name: v0.6.0, tag_name: v0.6.0"
]
---
cyberark/conjur-api-java
latest tag is v2.0.0
[
  "name: v2.0.0, tag_name: v2.0.0"
]
---
cyberark/conjur-api-python3
latest tag is v0.1.0
[]
---
cyberark/conjur-api-ruby
latest tag is v5.3.1
[
  "name: v5.3.1, tag_name: v5.3.1"
]
---
cyberark/conjur-authn-k8s-client
latest tag is v0.16.1
[
  "name: v0.16.1, tag_name: v0.16.1"
]
---
cyberark/secrets-provider-for-k8s
latest tag is v0.4.0
[
  "name: v0.4.0, tag_name: v0.4.0"
]
---
cyberark/conjur-service-broker
latest tag is v1.1.1
[
  "name: v1.1.1, tag_name: v1.1.1"
]
---
cyberark/cloudfoundry-conjur-buildpack
latest tag is v2.1.3
[
  "name: v2.1.3, tag_name: v2.1.3"
]
---
cyberark/ansible-conjur-host-identity
latest tag is v0.3.1
[
  "name: v0.3.1, tag_name: v0.3.1"
]
---
cyberark/conjur-credentials-plugin
latest tag is v0.8.0
[
  "name: v0.8.0, tag_name: v0.8.0"
]
---
cyberark/conjur-puppet
latest tag is v2.0.2
[
  "name: v2.0.2, tag_name: v2.0.2"
]
---
cyberark/terraform-provider-conjur
latest tag is v0.2.0
[
  "name: v0.2.0, tag_name: v0.2.0"
]
---
cyberark/secretless-broker
latest tag is v1.5.2
[
  "name: v1.5.2, tag_name: v1.5.2"
]
---
cyberark/summon
latest tag is v0.8.1
[
  "name: v0.8.1, tag_name: v0.8.1"
]
---
cyberark/summon-aws-secrets
latest tag is v0.3.0
[
  "name: v0.3.0, tag_name: v0.3.0"
]
---
cyberark/summon-chefapi
latest tag is v0.1.1
[
  "name: v0.1.1, tag_name: v0.1.1"
]
---
cyberark/summon-conjur
latest tag is v0.5.3
[
  "name: v0.5.3, tag_name: v0.5.3"
]
---
cyberark/summon-keyring
latest tag is v0.2.1
[
  "name: v0.2.1, tag_name: v0.2.1"
]
---
cyberark/summon-s3
latest tag is v0.2.0
[
  "name: v0.2.0, tag_name: v0.2.0"
]

```

**Comment by doodlesbykumbi** [comment]
So it looks like 
1. cyberark/conjur-aws doesn't have any tags
1. cyberark/conjur-api-python3's latest tag doesn't have a corresponding release

**Comment by izgeri** [comment]
nice!! we'll have to get the python3 maintainer to add a release to that latest tag ... (@sgnn7)

**Comment by sgnn7** [comment]
The 0.1.0 tag was only to push the docker cli container to dockerhub but that got stalled in mgmt. There's no user-facing change in that release.

**Comment by izgeri** [comment]
@sgnn7 how do you want to handle including that project in the suite? based on what's above, it looks like it doesn't meet the reqs yet

**Comment by sgnn7** [comment]
I don't think this is a very uncommon situation where we have a tag but no release - it's desired but it shouldn't be a requirement. I can maybe create a draft release for now?

**Comment by izgeri** [comment]
Maybe I misunderstood, but I thought the suite was querying releases and wouldn't see tags with no releases - I can wait to read more in your draft guidelines once you've got them up.

**Comment by sgnn7** [comment]
@izgeri : You are correct - @doodlesbykumbi ran a custom script to check the tags. Tags without releases won't be seen by the suite. More directly to the repo in question, 0.1.0 tag doesn't warrant a release right now so it should be invisible to the suite (it should pick up 0.0.5).

**Comment by sgnn7** [comment]
Resolution: tag deleted for now in python3 api repo

**Comment by izgeri** [comment]
@doodlesbykumbi @sgnn7 are we satisfied that this card is complete? 

we might be technically missing release instructions in each repo, but we've already ensured each repo links to the general CONTRIBUTING.md and that includes the general tag/release instructions now. so I think this part is done too.

**Comment by izgeri** [comment]
I'm going to mark it as complete, feel free to reopen if there's anything additional to do.
