### ISSUE TITLE
Repositories for projects in the OSS suite refer to the suite release docs page in their README

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-oss-suite-release#45]
AC:
- [x] Define a boilerplate that can be added to the top of repo READMEs to refer to the suite release / documentation
- [ ] Update repo READMEs for suite component repos to include this snippet early in the README

This should probably not be done until there is a suite release, but the boilerplate can be defined earlier.

**Comment by izgeri** [comment]
The list of suite release repos can be found [here](https://github.com/cyberark/conjur-oss-suite-release/blob/master/suite.yml) - every repo listed in the suite should have this heading at the top.

The URL that they will be pointing to is: https://docs.conjur.org/Latest/en/Content/ReleaseNotes/ConjurOSS-suite-RN.htm

Suggested boilerplate (@alexkalish please review):
> Are you using this project with [Conjur OSS](https://github.com/cyberark/conjur)? Then we **strongly** recommend choosing the version of this project to use from the [latest Conjur OSS suite release](https://docs.conjur.org/Latest/en/Content/ReleaseNotes/ConjurOSS-suite-RN.htm). Conjur maintainers perform additional testing on the suite release versions to ensure compatibility. For any questions, please contact us on [Discourse](https://discuss.cyberarkcommons.org/c/conjur/5)

Most projects have a "Usage" section in the README that would be an appropriate place to put this info.

**Comment by boazmichaely** [comment]
@izgeri I think it's good

**Comment by izgeri** [comment]
Noting here that @alexkalish suggested that for integrations, etc the Conjur version is fixed, and they should choose the latest suite release that matches their Conjur version.

I propose:
> Are you using this project with [Conjur OSS](https://github.com/cyberark/conjur)? Then we **strongly** recommend choosing the version of this project to use from the latest [Conjur OSS suite release](https://docs.conjur.org/Latest/en/Content/Overview/Conjur-OSS-Suite-Overview.html). Conjur maintainers perform additional testing on the suite release versions to ensure compatibility. When possible, upgrade your Conjur version to match the [latest suite release](https://docs.conjur.org/Latest/en/Content/ReleaseNotes/ConjurOSS-suite-RN.htm); when using integrations, choose the latest suite release that matches your Conjur version. For any questions, please contact us on [Discourse](https://discuss.cyberarkcommons.org/c/conjur/5)

**Comment by izgeri** [comment]
@BradleyBoutcher this is ready to go with the language above ^ can you please plan to work on this next week?

**Comment by izgeri** [comment]
Thanks @BradleyBoutcher for wrapping this up!
