### ISSUE TITLE
Suite release notes tell users how to deploy Conjur using the suite release version

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-oss-suite-release#67]
In the first release, we will tell users how to use docker-compose (quick start), the helm chart, and cloudformation templates with the suite release versions (eg share examples of how to configure with suite release versions) 

eg. deploy the helm-chart with a custom-values.yml that specifies the conjur version as [version from suite release] (then share example custom-values.yaml)

AC:
- [ ] Write up instructions (templated with the Conjur OSS version) that tell someone what instructions to follow to deploy Conjur OSS v1.x.y using:
   - [Quick start](https://github.com/cyberark/conjur-quickstart)
   - [Helm chart](https://github.com/cyberark/conjur-oss-helm-chart/tree/master/conjur-oss)
   - [Cloudformation Templates](https://github.com/cyberark/conjur-aws)
- [ ] Update the suite release notes auto-generation to include outputting the auto-detemplated instructions above in a `Deploying Conjur OSS` section

Note: the instructions should make liberal use of links to our existing documentation, and should only include custom information when there are special instructions a user must follow when deploying a specific Conjur version.

**Comment by izgeri** [comment]
@alexkalish I'm not sure we have upgrade instructions for Conjur OSS anywhere yet - so this feels dangerously close to out of scope. Is it valuable just to tell people how to deploy using the suite release version the first time? If we have users, they will need to know how to upgrade from their current version to this new release.

**Comment by alexkalish** [comment]
@izgeri: I don't know know of any upgrade instructions, but my familiarity with OSS details is unfortunately still a little lacking.  I think that there is probably something we can/should do in terms of linking to deployment methods.  Maybe just keep this open and we'll re-evaluate when the project is farther along and we have a more concrete UX?

**Comment by doodlesbykumbi** [comment]
I suppose something this effect should work:

---

### Upgrade instructions

Upgrading Conjur generally requires modifying the container image tag to the value in the release suite. Below are more specific instructions depending on environment.

For running on **Docker** (e.g. in the [quickstart docker-compose.yml](https://github.com/cyberark/conjur-quickstart/blob/master/docker-compose.yml) change the container image tag to:
```
image: cyberark/conjur:"<CONJUR_VERSION>"
```

For [**Cloud Formation templates for AWS**](https://github.com/cyberark/conjur-aws) set the environment variblae CONJUR_VERSION before building the AMI:
```
export CONJUR_VERSION="<CONJUR_VERSION>"
./build-ami.sh
```

For the [**Conjur OSS Helm chart**](https://github.com/cyberark/conjur-oss-helm-chart), the command takes the form :
```
helm install ... \
  --image.tag="<CONJUR_VERSION>" \
  ...
  https://github.com/cyberark/conjur-oss-helm-chart/releases/download/v<HELM_CHART_VERSION>/conjur-oss-<HELM_CHART_VERSION>.tgz
```
