### ISSUE TITLE
Spike: Design/architect the workflow for generating/storing suite release `repositories.yml`

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-oss-suite-release#81]
This is mostly just reserved time to find the appropriate approach to cutting a new suite release. Some discussion about this is [here](https://gist.github.com/izgeri/fc2b2341cdd8dad3ba49a97844e9cd2a) but ironing it out is needed.

AC:
- [ ] Direction in storing tagged suite releases is clear

**Comment by izgeri** [comment]
@sgnn7 is this a duplicate of #83 now? it seems to me like we have the direction now - but please confirm.

**Comment by sgnn7** [comment]
No - this task is to determine the nuances of #83 (naming to use, folder to use, etc) before we go implement things.

**Comment by sgnn7** [comment]
# Proposal

## Prerequisites

- Move `repositories.yml` -> `suite.yml`

## Process

- (manual) Tag gets created and pushed to repo
- (auto) Suite runs tests via GH actions and opens a draft release with included release notes
- (manual) Developer publishes the release
- (auto) GH actions see the publishing action and:
  - Removes any `releases/suite_<tag_name>.yml` file
  - Copies `suite.yml` -> `releases/suite_<tag_name>.yml`
  - Commits the changes to the repo
  - Pushes the repo update to `master` branch
  - TBD other steps that would get done here

One thing to note here is that in this impl the tag would point to a state of repo where `releases/` dir would not contain `suite_<tag_name>.yml` since that would require a tag re-write but `suite.yml` would be the right version.

**Comment by izgeri** [comment]
I want to make sure this fits in with the draft release process [here](https://gist.github.com/izgeri/fc2b2341cdd8dad3ba49a97844e9cd2a), or that we update that process appropriately

I think the only difference is really the step
> Copies `repositories.yml` to `releases/suite-x.y.z.yml` where `x.y.z` is the new suite release version.

In your proposed model, that would happen after the release is published. I think that's fine, and it's ok for the tagged commit to not have the archived file but have the current pinned versions in `suite.yml`.

it would be nice to see your outline integrated into the draft suite release instructions.

**Comment by sgnn7** [comment]
Looks like the draft release process is more inclusive of the things we need to do than my list here. The only significant divergence is the renaming of `repositories.yml` to `suite.yml`.

**Comment by sgnn7** [comment]
Closing this issue since for now https://gist.github.com/izgeri/fc2b2341cdd8dad3ba49a97844e9cd2a is close enough for the big details and I opened another story for renaming the main yml.
